name: 'Ignition CI'
description: 'Build and run tests for Ignition libraries.'
author: "Louise Poubel"
inputs:
  docker_image:
    description: "Docker image to use, defaults to ubuntu:bionic"
    required: false
    default: 'ubuntu:bionic'
  github-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  apt-dependencies:
    description: 'Dependencies to apt install'
    required: false
    default: ''
  codecov-token:
    description: 'Token to upload to Codecov'
    required: false
    default: ''
  cmake-args:
    description: 'Additional CMake arguments to use when building package under test'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docker_image }}
    - ${{ inputs.apt-dependencies }}
    - ${{ inputs.codecov-token }}
    - ${{ inputs.cmake-args }}

