name: 'Ignition install'
description: ''
author: "Louise Poubel"
inputs:
  github_token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
inputs:
  apt-dependencies:
    description: 'Dependencies to apt install'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apt-dependencies }}
