name: 'Ignition install'
description: ''
author: "Louise Poubel"
inputs:
  github_token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  apt-dependencies:
    description: 'Dependencies to apt install'
    required: false
    default: ''
  coverage:
    description: 'True to run coverage and upload results to Codecov'
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apt-dependencies inputs.coverage }}
