name: 'Ignition install'
description: ''
author: "Louise Poubel"
inputs:
  github_token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  apt-dependencies:
    description: 'Dependencies to apt install'
    required: false
    default: ''
  build-target:
    description: 'Thing to build with bazel'
    required: true
  test-target:
    description: 'Thing to build with bazel'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apt-dependencies }}
    - ${{ inputs.build-target }}
    - ${{ inputs.test-target }}
