name: 'Ignition install'
description: ''
author: "Louise Poubel"
inputs:
  github_token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  apt-dependencies:
    description: 'Dependencies to apt install'
    required: false
    default: ''
  codecov-token:
    description: 'Token to upload to Codecov'
    required: false
    default: ''
  cmake-args:
    description: 'Additional CMake arguments to use when building package under test'
    required: false
    default: ''
  gzdev_project_name:
    description: 'Project name to in gzdev repository configuration. Empty not to use gzdev'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apt-dependencies }}
    - ${{ inputs.codecov-token }}
    - ${{ inputs.cmake-args }}
    - ${{ github.repository }}
