on: [push]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ./
        with:
          apt-dependencies: 'libignition-math6-dev libignition-common3-dev'

